# Generated by Django 3.0.8 on 2020-08-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20200726_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('contato', models.CharField(max_length=10)),
                ('turno_atendimento', models.CharField(max_length=10)),
                ('newsletter', models.BooleanField(default=False)),
            ],
        ),
    ]
