# Generated by Django 3.0.8 on 2020-08-04 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_contatos_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='data_envio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 3, 22, 24, 0, 819257)),
        ),
    ]
